# Documentation Build Makefile
# Use with GNU make
#
# Copyright (C) 2003 The MARF Development Group
#
# $Header: /cvsroot/marf/marf/doc/Makefile,v 1.2 2003/02/10 08:52:35 mokhov Exp $

all distro clean maintainer-clean:
	make -C src $@

# EOF
