# MARF documentation makefile
# Use with GNU make
#
# Copyright (c) 2003 The MARF Development Group
#
# $Header: /cvsroot/marf/marf/doc/src/Makefile,v 1.3 2003/02/10 08:52:35 mokhov Exp $

all distro clean maintainer-clean:
	make -C tex $@

# EOF
